basePath: /v1
definitions:
  controller.UserSignUpRequest:
    properties:
      email:
        example: jon.doe@gmail.com
        type: string
      login:
        example: user1
        maxLength: 50
        minLength: 1
        type: string
      password:
        example: SuperPassword123
        type: string
    required:
    - email
    - password
    type: object
  response.Response:
    description: Structure for a standard API response
    properties:
      data: {}
      error:
        example: any error
        type: string
      status:
        example: success/error
        type: string
    type: object
info:
  contact:
    name: Evdokimov Igor
    url: https://t.me/epelptic
  description: API for potatorate site
  title: Film-catalog API
  version: 1.0.0
paths:
  /auth/sign-up:
    post:
      consumes:
      - application/json
      description: Registers a new user with the provided email and password.
      parameters:
      - description: User registration details
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/controller.UserSignUpRequest'
      produces:
      - application/json
      responses:
        "201":
          description: User successfully created
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Validation error or invalid request payload
          schema:
            $ref: '#/definitions/response.Response'
        "409":
          description: Conflict - User with this email already exists
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.Response'
      summary: User SignUp
      tags:
      - Authentication
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
